import Head from 'next/head'

export function Layout({children}){
    return (
        <>
        <Head>
        <title>Paradise Grow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/transparent/1.png" />
      </Head>
      <div className='layouts'>
        aaaaaaa
        {children}
      </div>


        </>
    )
}