import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Nav from　'../components/header'
import Items from '../components/product'
import Aboutus from '../components/about'
import Feature from '../components/feature'
import Contact from '../components/contact'
import Event from '../components/event'
import {Top} from '../components/top'
import {Footer} from '../components/footer'
import {Merit} from '../components/merit-weed'
import {useCallback} from 'react'
import { useRef, useEffect, useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const onScroll = useCallback((event) => {
    const { pageYOffset, scrollY } = window;
    const textElem = window.document.querySelectorAll('.title-anime')
    const opElem = window.document.querySelectorAll('.op-anime')

    for (let texti of textElem) {
      const textDistance = texti.getBoundingClientRect().top
      if (window.innerHeight > textDistance) {
        texti.classList.add('text-show')
      }
    }
    for (let opi of opElem) {
      const opDistance = opi.getBoundingClientRect().top
      if (window.innerHeight > opDistance) {
        opi.classList.add('op-show')
      }
    }
  }, [])
  useEffect(() => {
    window.addEventListener('scroll', onScroll, { passive: true })
    
})
  return (
    <>
      <Head>
        <title>Paradise Grow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/transparent/1.png" />
      </Head>

        <Nav></Nav>
        <Top arg="2"></Top>

<div className="bg-green-">

          <div className="h-40"></div>
          <Aboutus></Aboutus>
          <Merit></Merit>

          <Feature></Feature>
          <Items></Items>
          <Event></Event>
          <Contact></Contact>
          <Footer></Footer>
          

          </div>
    </>
  )
}
